# Generated by Django 5.0.4 on 2024-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('user_status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active'), ('T', 'Terminated')], max_length=1)),
                ('department', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
